### ISSUE TITLE
Inventory the ArcGIS Hubs

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#156]

**Comment by karenmajewicz** [comment]
- [ ] Check for broken portals
- [ ] Check that the title is still accurate

**Comment by karenmajewicz** [comment]
Also compare the arcPortals.csv to the items catalogued in the geoportal. Are the lists the same?


[geomg-export-2022-12-22.csv](https://github.com/geobtaa/metadata/files/10289228/geomg-export-2022-12-22.csv)

**Comment by ardumn** [comment]
08b-42133, http://data-yorkcountypa.opendata.arcgis.com/data.json, 

York County, PA GIS   Open Data Portal
