### ISSUE TITLE
Research ArcGIS Hubs and document basics

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#161]

**Comment by karenmajewicz** [comment]
ArcGIS Online vs ArcGIS Hub

**Comment by karenmajewicz** [comment]
How do organization upgrade their Hub site?

**Comment by ardumn** [comment]
Hubs:
Basic Overview ESRI ArcGIS Hub Site: [](https://www.esri.com/en-us/arcgis/products/arcgis-hub/overview )
Gallery of Examples of Hubs: [](https://doc.arcgis.com/en/hub/gallery/)
Built-in from Pro-West: [](https://www.prowestgis.com/services-products/esri-gis-solutions/arcgis-hub/)

ArcGIS Online:
Basic Overview ESRI ArcGIS Online Site [](https://doc.arcgis.com/en/arcgis-online/get-started/what-is-agol.htm#:~:text=ArcGIS%20Online%20is%20a%20cloud,being%20mobile%20in%20the%20field.)
Tons of Help Reference Links in One Place: [](https://doc.arcgis.com/en/arcgis-online/reference/faq.htm)

**Comment by karenmajewicz** [comment]
[Outline for ArcGIS Hub harvests](https://docs.google.com/document/d/10me4pcyh9_WV_3074vBVIF8OgHseTjZlLJxVJVkpoV8/edit#)

**Comment by karenmajewicz** [comment]
Create text content for the "Explanation" section.
