### ISSUE TITLE
Remediate coordinates for maps that have flagged bounding boxes

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#186]
Overview of the possible "Reasons" something might have been flagged:

- 'Global Bbox' = the bounding box is global in scale but doesn't have "World' or "Earth" as "Spatial Coverage"
- 'Crosses date line?' = max and min longitudes are opposite signs and are suspected of crossing the date line (but not the prime meridian)
- 'Tiny Bbox' = the bounding box is very small (and probably smaller than something that would appear on a map)
- 'Strange box shape' =  the bounding box is stretched N/S or E/W  - the larger the number in the column 'Box Shape', the greater the likelihood of an error.
- 'Missing Bounding Box' =  the item is missing a bounding box
- 'Negative longitude sign expected' = Missing negative signs for longitude values in maps with a "Spatial Coverage" matching a US state name

**Comment by karenmajewicz** [comment]
[Bbox_check_20230208-1.csv](https://github.com/geobtaa/metadata/files/10700829/Bbox_check_20230208-1.csv)

**Comment by karenmajewicz** [comment]
How should we tag maps that we have checked and verified that the bboxes are OK?

**Comment by karenmajewicz** [comment]
Add: "bbox verified" to Status field

**Comment by karenmajewicz** [comment]
https://boundingbox.klokantech.com

**Comment by ardumn** [comment]
[Bbox_check_20230208-1(updated).csv](https://github.com/geobtaa/metadata/files/10804961/Bbox_check_20230208-1.updated.csv)
