### ISSUE TITLE
Set up environment

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#266]
Tools & Modules needed:

- [ ] Anaconda / Mini-conda
- [ ] A conda environment for doing metadata
- [ ] jupyter notebook

Modules:
- [ ] pandas
- [ ] beautiful soup
- [ ] spacy

**Comment by karenmajewicz** [comment]
Use this issue to document the tools you install, which versions, and how you did it (i.e. conda vs pip)

**Comment by conno234** [comment]
Note: This process was done on an Intel MacBook Pro.

My first step was to go to the official Anaconda website's download page (https://www.anaconda.com/download). I selected the correct OS I wanted to download from the drop down screen at the bottom and began the download process.

The next step was to complete the installation process--once the Anaconda installer has finished downloading into my downloads folder, I clicked on it and it walked me through the rest of the installation process.

Once the installation is complete, I had a new app, "Anaconda-Navigator", in my application folder.

I opened Anaconda-Navigator and saw a number of applications on the home page that could be loaded or installed. For me, I downloaded Jupyter Notebooks and JupyterLab.

Using the tabs on the side of the navigator window, I switched from "Home" to "Environments". There should only be one entry in the middle column: "base (root)". By clicking the "Create Button" at the bottom of the window, you can create additional environments.

With a certain environment selected, I used "Search Packages" tool on the right of the window to search for packages I wished to install into my environment (note: make sure the package filters are set to "All", not "Installed", in the drop down at the top of the list). Once I a found a package that is not installed, I clicked the check box by it and clicked the apply button that shows up at the bottom right of the window. After loading, I was asked to load in more packages in some cases, in which case I just said yes.

Using this process, I added in a number of modules and packages that were requested to a new environment I called "Conda", the packages in question being conda, numpy, beautifulsoup, and spacy. I could then launch my environment a couple different ways. One is by moving over to the list of environments in the middle of the Environments tab, clicking on a environment, then clicking on the green play button that appears, where I could then select my chosen medium to launch the environment.

I can also return to the home tab of the Navigator, select the environment from the drop down at the top of the window, and then choosing from one of the applications below and pressing its "Launch" Button.
