### ISSUE TITLE
Create tutorial for changing paths

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#305]
We could use a tutorial that shows how to navigate folders and files using the command line. Then, we would demonstrate how to do write this within a Python script.

**Comment by karenmajewicz** [comment]
This will be "Tutorial #2 - changing paths"

sections:

title
purpose
intro text

Demonstration of changing paths

- move up one directory
- move up two directories
- move down ...
- identify a file in the same directory (.)

**Comment by karenmajewicz** [comment]
For next meeting: Start researching and compiling a list of commands related to changing paths and listing files by directory.

**Comment by conno234** [comment]
https://docs.google.com/document/d/1-uJGRD6wWnTiobnOLjEZhA37kHD9v7H9yKGmdp_ZmQU/edit?usp=sharing

**Comment by karenmajewicz** [comment]
This came out great! I like the messages at the end in the form of file names.
