### ISSUE TITLE
update 01b-18057 with correct landing page and reharvest

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#335]
This portal changed their URL and platform awhile ago, but I don't know where it went. Could you do some research to see if you can find an open data portal for Hamilton County, Indiana?

We have a record for the ArcGIS Online account (https://geo.btaa.org/catalog/gis1_hamiltoncounty_in_gov_portal_home), but I feel like there must be another portal somewhere.

**Comment by conno234** [comment]
Found this: https://geohub.hamiltoncounty.in.gov

**Comment by karenmajewicz** [comment]
@karen make a new issue for this

**Comment by karenmajewicz** [comment]
- [ ] update the website record with the fields as described here: https://gin.btaa.org/metadata/recipes/update-hub-list/
