### ISSUE TITLE
Organize the Index Map repository

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#36]

**Comment by Ziiiiing** [comment]
A new repo for all finished index maps: 
https://github.com/BTAA-Geospatial-Data-Project/published-index-maps


-----
**Questions:**
- In our [old repo](https://github.com/BTAA-Geospatial-Data-Project/indexmaps/tree/main/data/05d-01), we have a folder `05d-01` for all MN counties' Index Map, however, the GEOMG use another code `05d-02` instead. Which one should we follow?
- I cannot found the GEOMG link or Geoportal link for Le Sueur County, MN. But it does exist in the `05d-01` folder in our old index map repo.
- All links for Geoportal in the readme table should work, however, when I click the links from readme file, it does not work with the Internal Server Error(Error code: 500).

**Comment by karenmajewicz** [comment]
Q1: Use 05d-02

Q2: I will make a new one
