### ISSUE TITLE
Investigate Clean Recipe/Fuzzy Matching

### ISSUE THREAD

**Issue by conno234** [geobtaa/metadata#398]
The new "Clean" recipe produces this warning when you run it:

UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

**Comment by karenmajewicz** [comment]
I removed this module from the last PR so it is not an issue any longer.
