### ISSUE TITLE
Update WROC links in Wisconsin records

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#400]
message from WI Team member

> There abut 115 Wisconsin records for WROC aerial imagery that have broken links.  The files will have one of the following URLs:
> http://ncwrpc.org/WROC2020//wp-content/uploads/2014/06/WROC_2015_InfoSheet_v1.2.pdf
> https://ncwrpc.org/WROC2020/
>  
> Both URLs can be replaced with: https://www.ncwrpc.org/wisconsin-regional-orthoimagery-consortium-wroc/

**Comment by karenmajewicz** [comment]
There are still a few with this link that needs to be replaced: http://ncwrpc.org/WROC2020/

(there is not an `s` at the end of http)

**Comment by conno234** [comment]
apologies

**Comment by conno234** [comment]
Updated urls have been imported
