### ISSUE TITLE
Create new entry for Iowa Aerial Photo Indices

### ISSUE THREAD

**Issue by conno234** [geobtaa/metadata#487]
This needs to be added: 
Iowa Aerial Photo Indices: https://digital.lib.uiowa.edu/islandora/object/ui%3Aapi

**Comment by karenmajewicz** [comment]
05d-01

**Comment by karenmajewicz** [comment]
To do:

- [ ] Determine bounding boxes
- [ ] Determine IIIF links

**Comment by karenmajewicz** [comment]
https://geo.btaa.org/?f%5Bgbl_resourceClass_sm%5D%5B%5D=Imagery&q=03d-01&search_field=all_fields
