### ISSUE TITLE
Create new entry for GLO (General Land Office) Maps

### ISSUE THREAD

**Issue by conno234** [geobtaa/metadata#488]
This needs to be added:
GLO (General Land Office) Maps: https://digital.lib.uiowa.edu/islandora/object/ui%3Aglo

**Comment by karenmajewicz** [comment]
I need to update the metadata on these.

**Comment by karenmajewicz** [comment]
These are now reorganized as child records under 03d-01-03.  https://geo.btaa.org/catalog/03d-01-03
