### ISSUE TITLE
Improve metadata for new Iowa Digital Maps 03d-01

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#490]
- [x] Bounding Box: Fill in empty fields
- [x] IIIF: Spot check to see if these are working. You should get a valid JSON as a response. Some of the sets might not work, so indicate if you see any patterns.

**Comment by karenmajewicz** [comment]
[03d-01.csv](https://github.com/geobtaa/metadata/files/13588997/03d-01.csv)

**Comment by conno234** [comment]
[invalid_links.csv](https://github.com/geobtaa/metadata/files/13643688/invalid_links.csv)

Here is a list of invalid IIIF links from the CSV

**Comment by karenmajewicz** [comment]
Remove invalid links and upload to GBL Admin
