### ISSUE TITLE
Generate list of bboxes for all nations

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#504]
We need a list of the bounding boxes for countries.  [Create a new tab on this spreadsheet.](https://docs.google.com/spreadsheets/d/1YmJeTjflyWo081uBlmPG91_LnPvQSf6k3yjrP3ZFsgQ/edit#gid=1719787500)

You should be able to use ArcGIS: load a file of all nations and use a field calculation like the one found on the last tab of the spreadsheet (called Documentation)

**Comment by conno234** [comment]
https://docs.google.com/spreadsheets/d/1YmJeTjflyWo081uBlmPG91_LnPvQSf6k3yjrP3ZFsgQ/edit#gid=591597168

**Comment by karenmajewicz** [comment]
Round to 2 decimal places
