### ISSUE TITLE
03b-19029 annual review 2024-01

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#516]
- [x] Check for broken links
- [x] Assess if metadata (dates) are still accurate
- [x] Make a list of items that need to be retired
- [x] Make a list of items that need to be accessioned

**Comment by conno234** [comment]
All: Temporal coverage is 2019, published

*Cass County GIS Downloadable Files: Accessioned 4/2021, Updated 12/2023
*Blocks [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Lots [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Sections [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Subdivisions [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Townships [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Corporate Limits [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Parcels [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Qtr Section [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*County Boundary [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
*Qtr Qtr Section [Cass County, Iowa]: Accessioned 6/2020, Updated 9/2023
