### ISSUE TITLE
03c-01 Annual review 2024-01

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#517]
- [x]  Check for broken links
- [x]  Assess if metadata (dates) are still accurate
- [x]  Make a list of items that need to be retired
- [x]  Make a list of items that need to be accessioned

**Comment by conno234** [comment]
Temporal coverage: 2020

Website is still active and all records connect to shared download page (download links also work)

Website record was created 4/2021, updated 12/2023, accessioned 5/2020
Dataset records were created 4/2021, updated 9/2023, accessioned 6/2020
