### ISSUE TITLE
04b-24027 Annual review 2024

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#521]
- [ ]  Check for broken links
- [ ]  Assess if metadata (dates) are still accurate
- [ ]  Make a list of items that need to be retired
- [ ]  Make a list of items that need to be accessioned

**Comment by conno234** [comment]
- Website Record: created April 2021, last updated December 2023.
- Dataset records: Most recently accessioned records were from April 2019--layer description links connect to same website (Howard County, Maryland data download and viewer page) and some based on checking a few datasets, they can be still be found and downloaded. WFS layer and direct download URLs on GBL admin do not work however.

**Comment by karenmajewicz** [comment]
To do:

- [ ] determine platform of newest site
- [ ] unpublish old records
- [ ] determine new harvesting strategy

**Comment by karenmajewicz** [comment]
Unpublishing old records from static site.

Maintain the Socrata site. Currently, there are 5 records.
