### ISSUE TITLE
Create documentation for migrating OpenIndexMaps from v. 0 to v. 1.1

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#531]
see 

https://github.com/OpenIndexMaps/openindexmaps.github.io/issues/40

and 

https://github.com/geoblacklight/geoblacklight/issues/1325

**Comment by karenmajewicz** [comment]
Compare these tables

version 0 : https://openindexmaps.org/specification/0.0.0
version 1 : https://openindexmaps.org/specification/1.0.0

**Comment by karenmajewicz** [comment]
Put the possible fields for both specs into a spreadsheet

**Comment by conno234** [comment]
Found it--I originally made the notes as a Google Doc. Quickly converted it into a Google Sheet (feel free to edit it):
https://docs.google.com/spreadsheets/d/1Et-J8PQRdaElht2VxGVCPsXkO2CFlJp-YkcEqYx13po/edit?usp=sharing

**Comment by karenmajewicz** [comment]
Add this as a PR to OpenIndexMaps
