### ISSUE TITLE
Test multiple downloads workflow

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#542]
I am unsure of the best workflow for managing multiple downloads for continually harvested collections.  Questions to determine:

- When we update a collection, we re-import metadata records. This overwrites the existing record. If we re-import multiple downloads, are they overwritten? Added to?

- [ ] put together some test data
- [ ] import into dev site
- [ ] test if links overwrite or duplicate
- [ ] document a workflow

**Comment by conno234** [comment]
The "Multiple Downloads" page is producing warning saying download links could not be destroyed when one uploads the file to the Destroy function. Upon examination after multiple attempts, seemingly all relevant records listed in the inputted CSV did indeed have their download links removed.
![Screenshot 2024-02-01 at 4 45 44 PM](https://github.com/geobtaa/metadata/assets/135058788/874997cc-95d3-4380-b64d-c482ceab7d59)

**Comment by karenmajewicz** [comment]
Test record: https://geodev.btaa.org/admin/documents/test/edit

[test-multiple-downloads.csv](https://github.com/geobtaa/metadata/files/14195767/test-multiple-downloads.csv)

**Comment by karenmajewicz** [comment]
Conclusion:

1. We are getting **erroneous** messages saying links cannot be created or destroyed when we upload to a record with existing links.  The actions are actually successful - we just aren't getting the right messages.
2. Our workflow for updating records with multiple downloads is clumsy. We need to explore if there are better ways of doing this.
3. Regardless of the outcome, we need to document the workflow more explicitly.
