### ISSUE TITLE
05d-01 Harvest January 2024 Important Farmlands

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#545]
Use this harvest script: https://github.com/geobtaa/harvesting-guide/blob/main/recipes/R-09_05d-01-umedia/R-09_05d-01_umedia.ipynb

**Comment by karenmajewicz** [comment]
https://umedia.lib.umn.edu/search?facets%5Bcontributing_organization_name_s%5D%5B%5D=University+of+Minnesota+Libraries%2C+John+R.+Borchert+Map+Library.&q=farmlands&sort=date_added_sort+desc%2C+title_sort+asc

**Comment by conno234** [comment]
encountering internal server error for U-Media site

**Comment by karenmajewicz** [comment]
Something from Sept 2023 was causing the script to fail. I tried it again and was able to grab everything from Dec 2023-Jan 2024.
