### ISSUE TITLE
Add ArcGIS story map link

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#598]

**Comment by karenmajewicz** [comment]
Also create a geoportal record for it.

**Comment by conno234** [comment]
https://storymaps.arcgis.com/stories/c5888d46f39848aa9bd6479afcc6314a

**Comment by karenmajewicz** [comment]
Transfer to Karen

**Comment by conno234** [comment]
https://geo.btaa.org/admin/documents/1414-0000001/edit
