### ISSUE TITLE
chart 171 missing from https://geo.btaa.org/catalog/p16022coll230:261-index

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#601]
Chart 171 is in the printed index and is included in the map set, but was left out of the OpenIndexMap

https://geo.btaa.org/catalog/p16022coll230:261

**Comment by karenmajewicz** [comment]
Charts 170, 177, and 184 just link to the atlas record. And Chart 189 is not on the index.

**Comment by conno234** [comment]
I have added 171 and 189 to the geojson and fixed the links to 170, 177, and 184.
