### ISSUE TITLE
retire mcleod record

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#605]
Website still works, and all but one dataset have working download links:
-https://www.mcleodcountymn.gov/departments/public_works/gis_(mapping___surveying)/section_data_and_geodetic/index.php
-https://cms5.revize.com/revize/mcleod/ftp/GIS/ZCustomers/cdown0thru6.zip

**Comment by conno234** [comment]
https://geo.btaa.org/admin/documents/890afd08-7d72-4e83-a00e-428a688685f9/edit
