### ISSUE TITLE
Reaccession 08a-01

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#67]

**Comment by karenmajewicz** [comment]
https://github.com/geobtaa/workflows/tree/main/harvesting/08a-01_pasda

**Comment by ardumn** [comment]
Script ran and produced output CSV!

**Comment by karenmajewicz** [comment]
Updated scripts here: https://github.com/geobtaa/workflows/tree/main/harvesting/08a-01_pasda


- [ ] run datasetURLs.py
- [ ] run html2csv.py
- [ ] Delete the extraneous characters in the INFORMATION field and the ID field. They are enclosed by `['` and/or `']` which need to be removed.
- [ ] Fill in Resource Class (most will be `Datasets`.  Do a keyword search for Imagery or aerial on the title and fill those in with `Imagery`
- [ ] Date Range: Use the temporal coverage to create a value of `yyyy-yyyy`
- [ ] Upload these records to GEOMG as drafts

**Comment by karenmajewicz** [comment]
FYI - I am making notes on #132 on how to further work through the next steps.

**Comment by karenmajewicz** [comment]
Add Format column
Use the value "Files"

**Comment by karenmajewicz** [comment]
https://geo.btaa.org/catalog/08a-01
