### ISSUE TITLE
Update ArcGIS Recipe documentation

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#714]
Download this file: https://github.com/geobtaa/metadata/blob/main/docs/recipes/R-01_arcgis-hubs.md  and update the steps for the final section

**Comment by cleorose** [comment]
[R-01_arcgis-hubs-cleo-11-9-24.md](https://github.com/user-attachments/files/17689687/R-01_arcgis-hubs-cleo-11-9-24.md)
Current edited version of the archubs recipe md file. I've got a few remaining questions, including about conventions for bolding/italics, the organization/number of steps, and the formatting of the earlier steps. More changes may be needed, but all the updated content is added and formatted.

**Comment by karenmajewicz** [comment]
Submit this as a pull request

**Comment by karenmajewicz** [comment]
The new page is here: https://gin.btaa.org/metadata/recipes/R-01_arcgis-hubs/.  I updated the workflow figure to match the steps.

**Comment by cleorose** [comment]
closing this issue and deleting the branch; will open a new one for future changes.
